language: csharp
mono: none
dotnet: 2.1

install:
- dotnet restore

branches:
    only:
     - Peter
     - Bence
     - Dominik

script:
 - dotnet build
 - dotnet test MovieReviewTest/MovieReviewTest.csproj
